### ISSUE TITLE
Promotions Duplicate

### ISSUE THREAD

**Issue by MarcoBarber** [gabzon/experiensa-website#5]
Santa Marta Promotion is in Duplicate

**Comment by MarcoBarber** [comment]
http://colombia.experiensa.com/> Promotions > Santa Marta > Win 7 Chrome Version 51.0.2704.84 m also in IE 11 browser> User Public > Santa Marta appears twice in duplicate > Priority High

**Comment by gabzon** [comment]
Just to be clear, even though it is a duplication, it is NOT a bug! This visual issue comes from the fact that we are using the carousel component, which will display images in a carousel style.
Currently the carousel component is configure as follows:

- Low screen resolutions (phones) : 1 image
- Medium screen resolutions (tablets & laptops): 3 images
- High screen resolutions (Laptops & Desktops): 5 images

The duplications comes from the fact that the website had only 4 offers, which viewed from a high resolution screen the component will duplicate 1/4 offerts to be able to be seen in the 5 images carousel

I've added a new offert + I cropped all images so that they are the same size
